version: "3"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
  influxdb:
    image: influxdb:2.7-alpine
    ports:
      - "8086:8086" 
    volumes:
      - myInfluxVolume:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-oss:9.5.1
    ports:
      - 3000:3000

volumes:
  myInfluxVolume: